services:
  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: location-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - location-network

  # Backend API Service
  backend:
    build: .
    container_name: location-backend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - location-network
    volumes:
      # Mount source code for development hot reload
      - .:/app
      - /app/node_modules
    command: bun run dev

# Named volumes for data persistence
volumes:
  redis_data:
    driver: local

# Custom network for service communication
networks:
  location-network:
    driver: bridge
